//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// 2022_newProject.rc에서 사용되고 있습니다.
//
#define IDC_MYICON                      2
#define IDOKSKILL                       3
#define IDD_MY2022NEWPROJECT_DIALOG     102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_MY2022NEWPROJECT            107
#define IDI_SMALL                       108
#define IDC_MY2022NEWPROJECT            109
#define IDR_MAINFRAME                   128
#define IDB_BITDICE_1                   129
#define IDB_BITDICE_2                   130
#define IDB_BITDICE_3                   131
#define IDB_BITDICE_4                   132
#define IDB_BITDICE_5                   133
#define IDB_BITDICE_6                   134
#define IDB_BITDICE_0                   135
#define IDD_Engraving_E                 136
#define IDD_SKILL_K                     137
#define IDB_KNIGHT1_IMAGE               138
#define IDB_ENEMYGUN1                   139
#define IDB_ENEMYFASTDOG1               140
#define IDB_ENEMYTANKER1                141
#define IDB_ENEMYMACHINE                142
#define IDB_ENEMYMACHINE1               142
#define IDB_CRITICALMENT                145
#define IDB_NOOBIE_IMAGE                146
#define IDB_ASSASSIN1_IMAGE             147
#define IDD_WANDERER                    148
#define IDB_BITCARD_1                   149
#define IDB_WANDERER_1                  150
#define IDB_BITMAP1                     151
#define IDB_BITSKILLPOINT               151
#define IDD_TREASURE_P                  152
#define IDB_TREASURE_1_1                153
#define IDB_TREASURE_2_1                154
#define IDB_TREASURE_3_1                155
#define IDB_TREASURE_4_1                156
#define IDB_TREASURE_5_1                157
#define IDB_TREASURE_6_1                158
#define IDB_TREASURE_2_2                159
#define IDB_BITBS_TEST                  160
#define IDB_ENEMYGUN2                   161
#define IDB_ENEMYMACHINE2               162
#define IDB_ENEMYFASTDOG2               163
#define IDB_ENEMYTANKER2                164
#define IDB_TREASURE_7_1                165
#define IDB_GUNNER1_IMAGE               166
#define IDB_ENEMY_IMG_BLOOD             167
#define IDB_ENEMY_IMG_NORMALATK         168
#define IDB_TREASURE_8_1                169
#define IDC_BUTTON_STRUP                1000
#define IDC_BUTTON_DPUP                 1001
#define IDC_STATIC_STRTEXT              1002
#define IDC_STATIC_DPTEXT               1003
#define IDC_BUTTON_KNIGHT_0_0           1003
#define IDC_STATIC_STRPOINT             1004
#define IDC_BUTTON_KNIGHT_1_1           1004
#define IDC_BUTTON_HPUP                 1005
#define IDC_BUTTON_KNIGHT_1_2           1005
#define IDC_STATIC_DPPOINT              1006
#define IDC_BUTTON_KNIGHT_1_3           1006
#define IDC_STATIC_HPTEXT               1007
#define IDC_BUTTON_KNIGHT_2_1           1007
#define IDC_STATIC_HPPOINT              1008
#define IDC_BUTTON_KNIGHT_2_2           1008
#define IDC_BUTTON_FASTUP               1009
#define IDC_BUTTON_KNIGHT_2_3           1009
#define IDC_STATIC_FASTTEXT             1010
#define IDC_STATIC_GROUP_1              1010
#define IDC_STATIC_FASTPOINT            1011
#define IDC_BUTTON_ASSASSIN_0_0         1011
#define IDC_BUTTON_ASSASSIN_1_1         1012
#define IDC_BUTTON_CRIUP                1012
#define IDC_BUTTON_ASSASSIN_1_2         1013
#define IDC_STATIC_CRITEXT              1013
#define IDC_BUTTON_ASSASSIN_1_3         1014
#define IDC_STATIC_CRIPOINT             1014
#define IDC_BUTTON_ASSASSIN_2_1         1015
#define IDC_STATIC_MONEYPOINT           1015
#define IDC_BUTTON_ASSASSIN_2_2         1016
#define IDC_STATIC_MANATEXT             1016
#define IDC_BUTTON_ASSASSIN_2_3         1017
#define IDC_BUTTON_MANAUP               1017
#define IDC_STATIC_GROUP_2              1018
#define IDC_STATIC_MANAPOINT            1018
#define IDC_BUTTON_TECH_0_0             1019
#define IDC_STATIC_SKILLHELPTEXT        1020
#define IDC_BUTTON_TECH_1_1             1021
#define IDC_STATIC_SKILLPOINT           1022
#define IDC_STATIC_WANDERERTEXT         1023
#define IDC_BUTTON_TECH_1_2             1023
#define IDC_BUTTON_WANDERER1            1024
#define IDC_BUTTON_TECH_1_3             1024
#define IDC_BUTTON_WANDERER2            1025
#define IDC_BUTTON_TECH_2_1             1025
#define IDC_BUTTON_WANDERER3            1026
#define IDC_BUTTON_TECH_2_2             1026
#define IDC_BUTTON_TECH_2_3             1027
#define IDC_STATIC_ABOUTTEXT            1028
#define IDC_STATIC_GROUP_3              1028
#define IDC_STATIC_IMAGE_WANDERER       1030
#define IDC_BUTTON_TREASURESELECT       1031
#define IDC_STATIC_TREASUREMONEY        1032
#define IDC_STATIC_TREASURETEXT         1033
#define ID_32771                        32771
#define IDSTAT                          32772
#define ID_32773                        32773
#define IDSKILL                         32774
#define ID_32775                        32775
#define IDRESETGAMESTARTER              32776
#define ID_32777                        32777
#define IDTREASURE                      32778
#define ID_32779                        32779
#define ID_GAMESAVE                     32780
#define IDGAMESAVE                      32781
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
